### ISSUE TITLE
MatSidenav with MatNavList doesn't display without fullscreen

### ISSUE THREAD

**Issue by benneq** [angular/material2#10406]
#### Bug, feature request, or proposal:
**Bug:** When I use `mat-nav-list` inside `mat-sidenav` and have **no** `fullscreen` set on `mat-sidenav-container`, the Nav List won't display.

#### What is the expected behavior?
The Nav List should be visible

#### What is the current behavior?
Can't see the Nav List

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-xhtjip?file=app/app.component.html
Simply add / remove `fullscreen` from `mat-sidenav-container`

#### What is the use-case or motivation for changing an existing behavior?
Bug fix

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0 beta 7
Angular Material 6.0.0 beta 4
TypeScript 2.6.2
Chrome 65

#### Is there anything else we should know?
I guess the stackblitz example is enough :)

**Comment by Chan4077** [comment]
It can actually be seen, it's just very small:

![Small `MatNavList`](https://user-images.githubusercontent.com/20047125/37382312-24062216-277d-11e8-99f3-f920777ccede.jpg)

The `[fullscreen]` attribute is only a CSS wrapper. Nothing much:

https://github.com/angular/material2/blob/c490ac1482060d36071a52cb6e715b7552501499/src/lib/sidenav/drawer.scss#L41-L47

Which compiles to this:
```css
.mat-drawer-container[fullscreen] {
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    position: absolute;
}
.mat-drawer-container[fullscreen].mat-drawer-opened {
    overflow: hidden;
}
```
