### ISSUE TITLE
Incorrect toolbar height in mobile landscape mode

### ISSUE THREAD

**Issue by CarabineSK** [angular/material2#10674]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Toolbar height in landscape mode on mobile device should be 48px,
according to material specification. It was changed before because bug with virtual keyboard issues.
This toolbar now uses too much of vertical space to be used as app bar on mobile.

#### What is the current behavior?
Toolbar height in landscape mode on mobile device is 64px
![image](https://user-images.githubusercontent.com/6003253/38247361-4e00b770-3745-11e8-9c66-55a0bb2d5492.png)

#### What is the use-case or motivation for changing an existing behavior?
Application I want to create have very little vertical space.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.2.4

**Comment by DevVersion** [comment]
This is intentional. Previously we adjusted the height to `48px` if the mobile device is in landscape-mode. To avoid a jumping toolbar for most mobile users, we had to remove that logic (see https://github.com/angular/material2/commit/d1abc9ea06cdf796c9f279ef72688e43fb0fce62).

Also in the latest version of the Material Design specs (and the implementation of MDC), there is no special treatment for landscape-orientation anymore. A new dense mode has been introduced (tracked by https://github.com/angular/material2/issues/11878)

I'm going to close this issue because everything is worked as expected. If you personally want to reduce the height of the toolbar, you can always easily overwrite the height with some CSS.

```css
@media (max-width: 959px) and (orientation: landscape) {
  .mat-toolbar-multiple-rows {
    min-height: 48px;
  }
  .mat-toolbar-row, .mat-toolbar-single-row {
    height: 48px;
  }
}
```
