### ISSUE TITLE
mat-form-field: Form field outline gap has thin border on displays with non integer scaling

### ISSUE THREAD

**Issue by specialkk** [angular/material2#10710]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Form field outlines should have a uniform thickness 

#### What is the current behavior?
At 125% (highlighted):
![image](https://user-images.githubusercontent.com/4993980/38338217-8fd95f5c-3836-11e8-836f-f20d45326410.png)

At 150%:
![image](https://user-images.githubusercontent.com/4993980/38338163-579c45d2-3836-11e8-8e41-193ad36f6d4a.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-material2-issue-8frm4d

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 6 rc.0
Browsers: Chrome (65) - Firefox and Edge behave fine

#### Is there anything else we should know?
The exact cause seems to be that Chrome render borders with a border-radius set to have thicknesses rounded to the nearest physical device pixel. For example, on a 150% scale window, a `1px` border will be rendered as a 1px border with antialiasing causing it to bleed into the next row with transparent pixels (1.5 physical pixels). With a border-radius of `1e-6px` on the same border, there is no visible border radius, yet Chrome will render it equivalently to a `1.333px` border with completely opaque pixels (2 physical pixels).

So to describe a complete fix, it would be:
* Get rid of the `::before` pseudo element on `.mat-form-field-outline-gap` and just style the top border directly
* apply a border-radius of `1e-6px` to `.mat-form-field-outline-gap`

EDIT:
Including this SCSS in an external stylesheet fixes it for me 
```scss
.mat-form-field-appearance-outline {
  &.mat-form-field-can-float.mat-form-field-should-float {
    .mat-form-field-outline-gap {
      border-top-color: transparent;
    }
  }

  .mat-form-field-outline-gap {
    border: 1px solid currentColor;
    border-left-style: none;
    border-right-style: none;
    border-radius: 1e-6px;

    &::before {
      content: none !important;
    }
  }
}
```
