### ISSUE TITLE
mat-spinner color

### ISSUE THREAD

**Issue by iamimbohacker** [angular/material2#11024]
#### Bug, feature request, or proposal:
Please add directive to apply color (hex, rgb, whatever) to the mat-spinner. existing color that applies theming sucks. My primary, accent and warn colors are have their specific colors and I want to make spinner white in speficic place. why i can do that?

#### What is the expected behavior?
directive to mofidy COLOR of circle using HEX

#### What is the current behavior?
You can only apply theme colors (primary. accent. warn)

**Comment by crisbeto** [comment]
It doesn't make sense to have a directive for this, because changing the color is trivial using CSS. You can use this selector to change the color:

```css
.mat-spinner circle {
  stroke: #fff;
}
```

**Comment by Radivarig** [comment]
To set dynamically:
```html
<mat-progress-spinner [ngStyle]="spinnerStyle" ...
```
```ts
get spinnerStyle() { return {color: <custom_color>} }
```
```css
.mat-progress-spinner::ng-deep circle {
  stroke: currentColor;
}
```
