### ISSUE TITLE
option to disable the sidenavs transition animation

### ISSUE THREAD

**Issue by jmurphzyo** [angular/material2#1126]
#### Bug, feature request, or proposal:

feature
#### What is the expected behavior?

an option to disable the close/open transition
#### What is the current behavior?

if you alter the width/display/position it fires the sidenav transition.
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
do something that changes the sidenavs position/display/width
#### What is the use-case or motivation for changing an existing behavior?

it makes the look and feel of integrating other 3rd party libraries poor. (ie any 3rd party app that also intergrates a fullscreen mode.. ie ckeditor)
#### Which versions of Angular, Material, OS, browsers are affected?

latest

**Comment by willshowell** [comment]
I'm interested in this too. @jelbourn should it be reassigned?

**Comment by jelbourn** [comment]
@mmalerba and I are going to be exploring some potentially wider sidenav changes in the coming months that may address this.

**Comment by jelbourn** [comment]
You should be able to disable them now via Angular animations

**Comment by peterdobson** [comment]
How would you disable them via Angular animations @jelbourn ? Any pointers would be appreciated!

**Comment by eliteproxy7** [comment]
anyone have any info on this yet?

**Comment by peterdobson** [comment]
@eliteproxy7 try:

.mat-drawer-transition .mat-drawer-content {
    transition-duration: 0s !important;
}

**Comment by tmtron** [comment]
@peterdobson 
When we use NoopAnimationsModule, all animations are gone and we don't need the css anyway.
But the problem is that now all animations in the app are gone, not only for the side-nav/drawer!

Anyone knows how to only disable the side-nav transition?

**Comment by philip-firstorder** [comment]
This animation style is briefly visible during the transition on the mat-sidenav:
```html
<mat-sidenav style="animation: gen_css_kf_24 400ms linear 0ms 1 normal forwards running;"></mat-sidenav>
```

It calls the BrowserAnimationsModule generated keyframes [defined here](https://github.com/angular/angular/blob/03d2e5cb1d28fc612c459e6c820e78f6320168e1/packages/animations/browser/src/render/css_keyframes/css_keyframes_driver.ts#L18):
```css
@keyframes gen_css_kf_24 {
  0% {
    box-Shadow: none;
    visibility: hidden;
    animation-timing-function: cubic-bezier(0.25, 0.8, 0.25, 1);
    transform: matrix(1, 0, 0, 1, -72, 0);
  }
  100% {
    box-Shadow: none;
    visibility: visible;
    transform: none;
  }
}

I guess you need to toggle the properties yourself to make it work.
```
