### ISSUE TITLE
Add Instructions for overriding component styles through link tag in index.html

### ISSUE THREAD

**Issue by gopherkhan** [angular/material2#1273]
#### Bug, feature request, or proposal:

Documentation Update:

Currently ViewEncapsulation in Material components makes things extremely hard to style without using `::shadow` or `/deep/` combinators (both of which are currently being deprecated). 

We need to indicate to users that they can override component styles using a global CSS file, specified in the link tag of their index.html

Otherwise the components appear too rigid for actual use.
#### What is the expected behavior?

Documentation indicates easy way to customize styles for Materials components (e.g. link color on a card).
#### What is the current behavior?

No such documentation exists. Components appear excessively rigid/restrictive, as if you are locked in to specific styles, colors, etc.
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
#### Is there anything else we should know?

Referred here by Martin.

**Comment by jelbourn** [comment]
@gopherkhan FYI, only a handful of the component currently have ViewEncapsulation turned on (tabs, progress, tooltip). What's likely getting in your way is the ViewEncapsulation in your own components. [Here's an example of a component defining styles that affects other components by turning off ViewEncapsulation](http://plnkr.co/edit/FTb7IiDlqKjKGKvwevGy?p=preview). 

At this point, we don't want to encourage overriding of _any_ styles in Material; because we're still in alpha, our css classes and DOM structure **will** change. Once things are more stable, we plan on providing an API of classes that you're able to style.

**Comment by kuncevic** [comment]
@jelbourn can you provide any feedback on this one?

I am using `md-hint`, it is bringing its own styles, sitting in the head
```
<style>
.md-hint {
    display: block;
    position: absolute;
    font-size: 75%;
    bottom: -.5em;
}
...
<style>
```
I want to override the 'bottom' and set color for all `md-hint` in my project so I can do this <md-hint [ngStyle]="{'color': 'red', 'bottom': 'auto'}"> as per https://github.com/angular/material2/issues/348. But this way I have to repeat that for each `md-hint`.
How would you just specify the styles just in one place(css file) so the original .md-hint css class gets overriden?
Right now If I define my custom css in the global stylesheet it won't affect `md-hint` becasue global stylesheet loads before material styles so it gets overridden.  To use `important!` sounds a bit dirty.

**Comment by Snesi** [comment]
Yeah, it's a little hard to style the slider. If for example, you need to add a unit next to the label's value, the wrapper needs to be bigger, but in order to do so I've had to add global styles with `!important` everywhere.

```scss
.mat-slider-thumb-label {
  opacity: 1;
  right: -30px !important;
  top: -55px !important;
  width: 75px !important;
  height: 30px !important;
  border-radius: 10px !important;
  background-color: teal !important;
  transform: scale(1) rotate(0) !important;
  &::after {
    content: ' ';
    width: 20px;
    height: 20px;
    position: absolute;
    transform: rotate(45deg);
    bottom: 0;
    left: 28px;
    background-color: teal;
  }
}

.mat-slider-thumb-label-text {
  transform: rotate(0deg) !important;
  position: relative;
  opacity: 1 !important;
  left: -6px;
  // TODO: find a better way to add square meters
  &::after {
    content: ' m²';
    position: absolute;
    width: auto;
    height: auto;
    white-space: pre;
    color: white;
  }
}
```

To get this result:
<img width="393" alt="screen shot 2017-05-26 at 12 16 12" src="https://cloud.githubusercontent.com/assets/831197/26491046/2e7323ac-420e-11e7-8b62-7a82fcea5d4a.png">

Is there a better way to do this??

**Comment by willshowell** [comment]
@Snesi not necessarily better, but you can remove your `!important`s by increasing specificity of your styles

```css
.mat-slider.mat-slider-thumb-label-showing
.mat-slider-thumb-container
.mat-slider-thumb-label {
  opacity: 1;
  right: -30px;
  top: -55px;
  width: 75px;
  height: 30px;
  border-radius: 10px;
  background-color: teal;
  transform: scale(1) rotate(0);
}
```
