### ISSUE TITLE
MatSelect panelClass example uses wrong CSS selector

### ISSUE THREAD

**Issue by arlowhite** [angular/material2#13693]
#### Bug, feature request, or proposal:

https://material.angular.io/components/select/overview#adding-custom-styles-to-the-dropdown-panel
The `panelClass` demo has no effect.

This is because the CSS rules are wrong.

#### What is the expected behavior?

Demo should show background color.

#### What is the current behavior?

CSS styles have no effect and do not demonstrate the feature.

#### What are the steps to reproduce?

https://material.angular.io/components/select/overview#adding-custom-styles-to-the-dropdown-panel
Switch to different colors, no styles change.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

7.0.0

#### Is there anything else we should know?

`.mat-select-panel` is not a child element of the panel, both classes are on the same element.
To fix this, just remove the space in the CSS selector.
From:
```css
.example-panel-red .mat-select-panel {
  background: rgba(255, 0, 0, 0.5);
}
```
To:
```css
.example-panel-red.mat-select-panel {
  background: rgba(255, 0, 0, 0.5);
}
```

I have not checked if other demos make this mistake.
