### ISSUE TITLE
Cannot set focus using ElementRef on input field with placeholder attribute (IE 11 only)

### ISSUE THREAD

**Issue by oleggiris** [angular/material2#14544]
#### What is the expected behavior?
If a input field has a placeholder attribute it should display caret and user should be able to type if element is focused by using nativeElement.focus() (works in Edge, Chrome, Firefox)

#### What is the current behavior?
Input is highlighted as it is focused, but no cursor appeared in input field and you cannot type.
![image](https://user-images.githubusercontent.com/12562145/50087702-fa62f680-0211-11e9-956e-386364f6f78d.png)

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-r9pkqf

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Typescript: 3.1.1
Angular: 7.0.1
Angular Material: 7.1.1
IE 11: 11.407.17134.0
Windows 10

**Comment by crisbeto** [comment]
If I remember correctly, IE moves focus asynchronously so your callback might be firing too early. Have you tried increasing the `setTimeout` duration?

**Comment by obytsiuk** [comment]
@oleggiris 
The issue is with `user-select` CSS property set on `.mat-input-element` placeholder:
https://github.com/angular/material2/blob/b5848889094949c02dc4aa6879aff3ebfd390a3b/src/lib/form-field/form-field-input.scss#L90
It prevents IE from placing the cursor inside the field (but not from firing `focus` event).

As a quick fix I've added this to `styles.scss`:

```scss
.mat-input-element {
  @include input-placeholder {
    // Default user-select: none prevents from focusing input correctly in IE
    -ms-user-select: auto !important;
  }
}
```
