### ISSUE TITLE
block-scroll-strategy: some styles will cause not working as expected

### ISSUE THREAD

**Issue by HsuanXyz** [angular/material2#15051]
#### What is the expected behavior?

documentElement fixed the position and block scrolling.

#### What is the current behavior?

documentElement the position offset.

#### What are the steps to reproduce?

![cdk-scroll](https://user-images.githubusercontent.com/22736418/52102238-5f37ac00-261a-11e9-8731-22adb5b62b47.gif)

```css
html, body {
  width: 100%;
  height: 100%;
}

body { 
  overflow-x: hidden;
}
```

StackBlitz: https://stackblitz.com/edit/angular-cgmaeh

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

`@angular/cdk 7.3`
