### ISSUE TITLE
theming with md-card , not working?

### ISSUE THREAD

**Issue by stefanaerts** [angular/material2#1767]
#### What is the expected behavior?
to have a background color based on theming like you can do with md-toolbar.

#### What is the current behavior?
i tried md-card color="primary" and background-color="primary".

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Is there anything else we should know?
If i have an existing card with a card image and title and subtitle.
How can i apply theming?

**Comment by stefanaerts** [comment]
So in this picture i want the color of the card to be purple based on the primary color of my theme,like the toolbar i put on top as an example
![image](https://cloud.githubusercontent.com/assets/3684599/20100440/cc393a1a-a5bd-11e6-8f9b-b464f17c7ec6.png)

**Comment by stefanaerts** [comment]
is it possible after i imported a theme scss file in my scss to get the $primary variable and assign
it to a color property in a created class?
something like this 

@import '~@angular/material/core/theming/prebuilt/deeppurple-amber';

.myclass{
color: $primary;
}

**Comment by leocaseiro** [comment]
You might want to use the mixin `md-color` with SASS:

```scss
@import '~@angular/material/core/theming/prebuilt/deeppurple-amber';
@include md-core(); // include all mixins

.myclass {
    color: md-color($primary, 500, 1);
}
```
