### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#205]
https://www.google.com/design/spec/style/typography.html

Combination of documentation and CSS.

**Comment by sendilkumarn** [comment]
can we add it per component or use typography.scss ?

**Comment by sendilkumarn** [comment]
if this is fine I will update the remaining components

**Comment by jelbourn** [comment]
To clarify: this issue is about making typography styles available for users to have in their own applications. I'm going to mark it as blocked since this will be influenced by how we approach theming as well.

**Comment by michaelwarren1106** [comment]
what's the implementation plan for typography? Are you guys planning on making this be a web component, or basically a stylesheet that will need to be imported/required into app components individually?

I've been debating the "proper" approach to typography and how best to componentize re-usable styles that generally are "global" in nature but dont really need a web component to be executed.

If you could outline some thoughts on your approach and the pros/cons thereof, that would be awesome!

**Comment by jelbourn** [comment]
Current thinking is to have an `@angular2-material/typography` package that includes a css file that you can drop into a `<link>` element in your index.html (or concat into other css files with your own build). We haven't finalized on this approach yet, though.

**Comment by michaelwarren1106** [comment]
with shadomDOM coming, and native in angular2, will that approach work? I've done a little bit of testing and it seems that this approach wont work since styles in the parent page wont bleed into a shadowDOM component...

**Comment by kylecordes** [comment]
I stumbled across this today while looking for an answer to the following: For applications starting to use Angular Material 2 today, prior to the typography implementation, what is best interim short-term solution for styling application content that is not a angular-material Component? For example, is it best to grab one of the other Material implementations, and use it alongside, for styling other content? Any advice for which one fits in with the least trouble?

**Comment by krigton** [comment]
Does it makes sense using typography from material 1 (no webcomponents usage yet), untill this at least started?

**Comment by krigton** [comment]
Will typography support theming? Like using different font for md-display and body copy.

thanks

**Comment by michaeljota** [comment]
@krigton it's blocked cause of theming, so I would say it will.

**Comment by shlomiassaf** [comment]
We've started using a webpack loader to override styles, since CSS comes bundled in we can't actually change much, only colors.

We also had hard time changing the font.

This is the loader [angular2-restyle-loader](https://github.com/shlomiassaf/angular2-restyle-loader)
It's fresh out of the oven.

We use it to re-compile SCSS so we can set the variables.
It can also do a lot more with higher maintenance risk.

For example, you can restyle the slide toggle  
![image](https://cloud.githubusercontent.com/assets/5377501/21007867/c12bf73c-bcf3-11e6-9c51-1b141c4d4a93.png)

To this:  
 ![image](https://cloud.githubusercontent.com/assets/5377501/21007829/812c6d92-bcf3-11e6-8fed-02d750e68ca5.png)

**Comment by cloudinertia-system** [comment]
I have combined a few SCSS libraries, cleaned up the code, and compiled a SCSS typography implementation that accurately follows the material design specification. The typography is responsive based on the component's dimensions optimized for flexbox. The font-colors adjust to the component's theme in accordance with web accessibility guidelines. Dynamic font imports are supported. Implementation options are flexible via SCSS mixins, custom css namespaces, and/or generated classes which make style specificity simple available globally, and at the component level. Maintenance and extensibility aspects were considered. I have never contributed to github before, and would appreciate any guidance.

**Comment by the-ult** [comment]
@jelbourn 
What is the status of the typography and theming?

> Current thinking is to have an @angular2-material/typography package that includes a css file that you can drop into a <link> element in your index.html (or concat into other css files with your own build). We haven't finalized on this approach yet, though.

i.e.:
I would like to use another font instead of the robot-font., so that it will be used for material components as well. What/where would be the proper way to define/overwrite the Roboto font?

**Comment by michaelz** [comment]
I used the following css to override the font, while waiting for another solution:

```scss
/*
 * Override default material design fonts ($mat-font-family)
 */

$mat-font-family: 'Titillium Web',
sans-serif;
.font-override { // body or wrapper class
  .mat-button-toggle,
  %mat-button-base,
  .mat-button,
  .mat-raised-button,
  .mat-fab,
  .mat-icon-button,
  .mat-mini-fab,
  .mat-card,
  .mat-checkbox,
  .mat-input-container,
  .mat-list,
  .mat-menu-item,
  .mat-radio-button,
  .mat-select,
  .mat-list .mat-list-item .mat-list-item-content,
  .mat-nav-list .mat-list-item .mat-list-item-content,
  .mat-simple-snackbar,
  .mat-tab-label,
  .mat-slide-toggle-content,
  .mat-toolbar,
  .mat-tooltip  {
    font-family: $mat-font-family !important;
  }
}

```
This can be improved I guess.
