### ISSUE TITLE
this dialog style is not work,seems no have

### ISSUE THREAD

**Issue by Striveyazi** [angular/material2#2228]
i use your demo code , but the css style is wrong, can you tell me that what are the possible causes of this error.
demo link:
https://github.com/angular/material2/blob/master/src/demo-app/dialog/dialog-demo.ts

error style:
![image](https://cloud.githubusercontent.com/assets/18276182/21208683/7dee1e84-c2aa-11e6-918c-2c737824caf5.png)
expect style:
like this 
![image](https://cloud.githubusercontent.com/assets/18276182/21208730/e064911a-c2aa-11e6-9e20-4a325b675aaa.png)
 i need your help

**Comment by crisbeto** [comment]
These are the proper dialog styles. We recently switched to using flexbox to center the dialog (see https://github.com/angular/material2/pull/1962), instead of `transform`, because using transforms can cause the dialog contents to become fuzzy in certain conditions (e.g. when the dialog's width or height isn't a whole number). Are you experiencing any rendering issues?

**Comment by Striveyazi** [comment]
thank u very much. your mean is cleaning node_modules/@angular or  node_modules/@angular/material  and reinstalling this.
i have done both . the position still is incorrect?

**Comment by Striveyazi** [comment]
angular version: 2.3.0
material verison:2.0.0-alpha.11-3

**Comment by crisbeto** [comment]
Both should do the trick. Also clearing the `node_modules` should be fine. Otherwise can you post a screenshot of what the dialog looks like for you?

**Comment by Striveyazi** [comment]
![image](https://cloud.githubusercontent.com/assets/18276182/21216497/201ab5dc-c2e2-11e6-8e75-9871051b38ce.png)

**Comment by Striveyazi** [comment]
![qq 20161215161823](https://cloud.githubusercontent.com/assets/18276182/21216525/3e95611a-c2e2-11e6-895f-f56aab084d92.png)

**Comment by Striveyazi** [comment]
i need it in center , or i can  custom  this position. my css style maybe cause  this problem? or not it's version problem?

**Comment by crisbeto** [comment]
It should be in the center by default. I'm trying it out locally and it works fine. It's hard to know what is going on just by looking at a screenshot, but the following CSS rules are what makes it work, in addition to the ones that are set as inline styles:

```css
.md-overlay-container {
  position: fixed;
  z-index: 1000;
}
.md-overlay-container, .md-global-overlay-wrapper {
  pointer-events: none;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
}

.md-global-overlay-wrapper {
  display: flex;
  position: absolute;
  z-index: 1000;
}
```

If these aren't in your stylesheet, then it's probably outdated.
