### ISSUE TITLE
We shouldn't have to rewrite classes to theme Material2

### ISSUE THREAD

**Issue by ThiagoT1** [angular/material2#233]
I was able to "theme" a button with this:

``` scss
@import '../node_modules/@angular2-material/core/style/theme-functions';
@import '../node_modules/@angular2-material/core/style/palette';

// Person creating a theme writes variables like this:
$md-is-dark-theme: false;

$md-primary: md-palette($md-purple, 500, 100, 700, $md-contrast-palettes);
$md-accent: md-palette($md-red, A200, A100, A400, $md-contrast-palettes);
$md-warn: md-palette($md-orange, 500, 300, 800, $md-contrast-palettes);
$md-foreground: if($md-is-dark-theme, $md-dark-theme-foreground, $md-light-theme-foreground);
$md-background: if($md-is-dark-theme, $md-dark-theme-background, $md-light-theme-background);

.app {
  .md-primary[md-raised-button] {
    color: md-color($md-foreground, text); 
    background-color: md-color($md-primary, 700, 0.7); // Use a specific hue and opacity
  }
}
```

This means I would need to "rewrite" virtually every class of default_theme.

However, if the below worked, this wouldn't be needed, as a full css sheet would be compiled, using the desired palletes:

``` scss
@import '../node_modules/@angular2-material/core/style/variables';
@import '../node_modules/@angular2-material/core/style/shadows'; 
@import '../node_modules/@angular2-material/core/style/theme-functions';
@import '../node_modules/@angular2-material/core/style/default-theme';
@import '../node_modules/@angular2-material/button/_button-theme.scss';

// Person creating a theme writes variables like this:
$md-is-dark-theme: false;

$md-primary: md-palette($md-purple, 500, 100, 700, $md-contrast-palettes);
$md-accent: md-palette($md-red, A200, A100, A400, $md-contrast-palettes);
$md-warn: md-palette($md-orange, 500, 300, 800, $md-contrast-palettes);
$md-foreground: if($md-is-dark-theme, $md-dark-theme-foreground, $md-light-theme-foreground);
$md-background: if($md-is-dark-theme, $md-dark-theme-background, $md-light-theme-background);


@import '../node_modules/@angular2-material/button/_button-base.scss';
@import '../node_modules/@angular2-material/button/button.scss';
```

Result:
![buttontheming](https://cloud.githubusercontent.com/assets/16569217/14061247/1ed8de36-f35a-11e5-9b83-418e10cee569.png)

This does not actually work, because styles living in documents head <style> element will always have priority on those declared inside a referred css file. If it worked, it would have the side effect of increasing the app size, since these styles are already contained on every Component styleUrls option.

Can I get some guidance on this, please?
