### ISSUE TITLE
Reflect internal element in md-input-container

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#2385]
#### What is the expected behavior?
`MdInputContainer` should reflect the internal element it wraps (input, textarea) via CSS class or an attribute.

#### What is the current behavior?
`MdInputContainer` does not reflect the internal element it wraps.

#### What is the use-case or motivation for changing an existing behavior?
CSS customization that differentiate between input a& textarea 

In order to customize some of the elements inside the container based on the element (input or textarea) the host element need to reflect it.

Since the wrapped element (input or textarea) is deep it's not possible to style any elements using selectors.

For example, to change the underline style for textarea so it displays a bit different then input you need a selector based on that states, not possible at the moment.

**Comment by benjamincharity** [comment]
Could you use `/deep/`in your styles? That's how I'm managing to tweak some styles for other 3rd party libraries I'm using.

> More Info on `/deep/` [here](https://angular.io/docs/ts/latest/guide/component-styles.html#!#-deep-)

Quick example:

```html
<md-input-container>
  <input />
</md-input-container>

<md-input-container>
  <textarea></textarea>
</md-input-container>
```

```scss
md-input-container {
  /deep/ input {
    // input styles
  }

  /deep/ textarea {
    // textarea styles
  }
}
```

**Comment by shlomiassaf** [comment]
Using `deep` is just making your selector stronger against other selector since you get that extra class name from the host.

This is not the case here since the host does not reflect the state (textarea/input) and if you want to change some element that is not a sibling of textarea (or ancestor of it) you just cent.

**Comment by benjamincharity** [comment]
I'm not sure I follow.. Using deep would actually do the opposite of make the selector stronger.


Here I cannot target a input that is generated by a 3rd party since the 3rd party won't include the `[_ngcontent-xkw-63]` attribute on their own DOM element:

```scss
// Fake code:
.foo {
  input {
    color: red;
  }
}

// Output:
.foo[_ngcontent-xkw-63] input[_ngcontent-xkw-63] {
  color: red;
}
```


Below, I _can_ target the input because `/deep/` told Angular to not add the component attribute to the input selector:

```scss
// Fake code with deep:
.foo {
  /deep/ input {
    color: red;
  }
}

// Output from deep:
.foo[_ngcontent-xkw-63] input {
  color: red;
}
```



Apologies if I haven't fully understood your issue!
