### ISSUE TITLE
how to override the height of md-list-item inside md-nav-list?

### ISSUE THREAD

**Issue by goldenbearkin** [angular/material2#346]
HTML:
```html
<md-list-item _ngcontent-ook-11="" role="listitem">
  <div class="md-list-item">
    <div class="md-list-text"></div>
    Pepper 
  </div>
</md-list-item>
```
CSS:
```css
md-list md-list-item .md-list-item, md-list a[md-list-item] .md-list-item, md-nav-list md-list-item .md-list-item, md-nav-list a[md-list-item] .md-list-item {
    ...
    height: 48px;
    ...
}
```
Seems the css class="md-list-item" is setting the row height to 48px. Given the css class should be encapsulated  by the md-list-item component. Is it possible to override the height without touching the compoent internal css?

**Comment by goldenbearkin** [comment]
```css
md-nav-list a[md-list-item] /deep/ .md-list-item {
  height: 30px;
}
```
The solution i got so far is putting the /deep/ combinator, but still not sure if it is the elegant way.
