### ISSUE TITLE
I want to show md-tooltip on a text element when the length of text exceeds specific length.

### ISSUE THREAD

**Issue by amaneer94** [angular/material2#3531]
#### Bug, feature request, or proposal:
I want to show dotted end text with fixed length but with tooltip when it exceeds specific text length.

**Comment by thomaspink** [comment]
```css
.mat-tooltip {
  max-width: 50px;
  /* or */
  /* width: 50px; */
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
