### ISSUE TITLE
multiple theme - mdslider not apply theme

### ISSUE THREAD

**Issue by deblockt** [angular/material2#4075]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
mdSlider need use theme specified by class

#### What is the current behavior?
mdSlider use default theme

#### What are the steps to reproduce?
Create a multiple theme

``` scss

// Define the default theme (same as the example above).
$candy-app-primary: mat-palette($mat-indigo);
$candy-app-accent:  mat-palette($mat-pink, A200, A100, A400);
$candy-app-theme:   mat-light-theme($candy-app-primary, $candy-app-accent);
@include angular-material-theme($candy-app-theme);

// second theme
$theme2-primary: mat-palette($mat-red);
$theme2-accent:  mat-palette($mat-green, A200, A100, A400);
$theme2-warn:    mat-palette($mat-deep-orange);
$theme2-theme:   mat-light-theme($theme2-primary, $theme2-accent, $theme2-warn);

.theme2 {
    @include angular-material-theme($theme2theme);
}
```

Use mdSlider like this : 
``` html
<div [class.theme2]="theme2">
         <button (click)="theme2 = !theme2">switch</button>
         <md-slider color="primary" thumbLabel ></md-slider>
</div>
```

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, browsers are affected?

Angular : 4.0.1
Material : 2.0.0-beta.3

#### Is there anything else we should know?

Same behaviour on input placeholer.

I'have temporary fix the issue whith this mixin : 
```scss
@mixin fix-angular-material-theme($theme) {
    @include angular-material-theme($theme);
    $primary: map-get($theme, primary);

    // slider color fix
    .mat-primary .mat-slider-track-fill, .mat-primary .mat-slider-thumb, .mat-primary .mat-slider-thumb-label {
        background-color: mat-color($primary) !important;
    }
}
```
