### ISSUE TITLE
How to change md-icon size

### ISSUE THREAD

**Issue by gtzinos** [angular/material2#4422]
Hello,

I use the class "md-24" on my md-icon but it doesn't work.

Here is a workaround but am i missing an official way ?

.material-icons.md-18 {
font-size: 18px !important;
height: 18px !important;
width: 18px !important;
}
.material-icons.md-24 {
font-size: 24px !important;
height: 24px !important;
width: 24px !important;
}
.material-icons.md-36 {
font-size: 36px !important;
height: 36px !important;
width: 36px !important;
}
.material-icons.md-48 {
font-size: 48px !important;
height: 48px !important;
width: 48px !important;
}

**Comment by donroyco** [comment]
As @jelbourn [mentioned](https://github.com/angular/material2/issues/1891#issuecomment-261411358) in #1891: 

> We would recommend people use css to size the icons.

**Comment by gtzinos** [comment]
Okay thank you.

**Comment by mackelito** [comment]
How can we do that on component basis?
```
:host {
  .mat-icon {
    width: 100px;
    height: 100px;
  }
}
```
This will not be applied.

**Comment by willshowell** [comment]
@mackelito I suspect you also need font-size

```scss
@mixin md-icon-size($size: 24px) {
  font-size: $size;
  height: $size;
  width: $size;
}

.mat-icon {
  @include md-icon-size(16px);
}
```

**Comment by mackelito** [comment]
Tried it but it´s not working.
I suspect it has something to do with how :host works?

my setup is that I have a <logo> component that contains <md-icon svgIcon="logo"></md-icon>

**Comment by kara** [comment]
Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.

**Comment by mackelito** [comment]
To continue: https://stackoverflow.com/questions/43887701/how-to-change-md-icon-size-in-material

**Comment by phamaimy** [comment]
change font-size of md-icon
Ex: font-size: 50px;
i have a problem the same, and that is my solution! :)

**Comment by naivefun** [comment]
try this scss:
```scss
.mat-icon-button.small {
  width: 32px;
  height: 32px;
  line-height: 32px;

  .mat-icon, .mat-icon-button i {
    line-height: 16px;
  }

  .mat-icon {
    width: 16px;
    height: 16px;
  }

  .material-icons {
    font-size: 16px;
  }
}
```
