### ISSUE TITLE
Accent inputs show wrong underline color when invalid

### ISSUE THREAD

**Issue by willshowell** [angular/material2#4651]
#### Bug, feature request, or proposal:
Bug

#### Expected behavior
The accent underline changes to error color, as it does for primary inputs.

#### Current behavior
The underline remains the accent color.

#### Repro
http://plnkr.co/edit/DOt4Wa1nBloTDSSEejPO?p=preview

**Comment by ocarreterom** [comment]
The placeholder color also toggles to accent/error on focus/blur.

**Comment by willshowell** [comment]
Workaround in the mean time

```scss
// Override until angular/material2/pull/4771
$warn: map-get($theme, warn);
$input-underline-color-warn: mat-color($warn);
.mat-input-container.mat-input-invalid {
  .mat-input-placeholder {
    &, &.mat-accent, &.mat-float .mat-placeholder-required {
      color: $input-underline-color-warn;
    }
  }
  .mat-input-ripple {
    &, &.mat-accent {
      background-color: $input-underline-color-warn;
    }
  }
}
```
