### ISSUE TITLE
Make slider thumb label always visible

### ISSUE THREAD

**Issue by michaelpwilson** [angular/material2#4803]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behaviour?

I would like the thumb label to remain visible, not just when the slider is being changed.

#### What is the current behaviour?

The slider thumb label will only show when the slider is being moved.

https://material.angular.io/components/component/slider

#### What is the use-case or motivation for changing an existing behaviour?

I don't think existing behaviour should be changed, but maybe an input can be given to ```<md-slider>``` which tells it whether to always display the thumb label.

From a design point of view, it is nice to be able to let the user know what the current value is for the slider.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

TypeScript 2.3.3
Angular 4.1.3
Angular Material 2.0.0-beta.5

**Comment by ocarreterom** [comment]
The slider is following the MD specs https://material.io/guidelines/components/sliders.html#sliders-discrete-slider

**Comment by ocarreterom** [comment]
The slider is following the MD specs https://material.io/guidelines/components/sliders.html#sliders-discrete-slider

**Comment by willshowell** [comment]
@michaelpwilson you can override it with css for now if you wish

```css
.mat-slider-thumb-label {
  transform: rotate(45deg) !important;
  border-radius: 50% 50% 0 !important;
}

.mat-slider-thumb {
  transform: scale(0) !important;
}

.mat-slider-thumb-label-text {
  opacity: 1 !important;
}
```
