### ISSUE TITLE
Allow to manage overflow within md-sidenav-layout

### ISSUE THREAD

**Issue by cortopy** [angular/material2#487]
* **Do you want to request a *feature* or report a *bug*?**

feature

* **What is the current behavior?**

The following won't work if the layout of the whole application is to take 100% of the height

```SASS
md-sidenav-layout
  height: 100%

  md-content
    height: inherit
```

If there is a Component too large within md-content, the whole page will scroll, including the sidebar if it's open and any top toolbars. In this instance, changing the css of the sidenav component to:

```CSS
  :host > md-content {
    position: relative;
    height: inherit
    -webkit-transform: translate3D(0, 0, 0);
            transform: translate3D(0, 0, 0);
    display: block; }
```

allows adjusting the `overflow` of children components within the main area using percentages. Percentages will not work unless the height of `md-content` is set. The advantage of this approach is that sidenav can stay open and won't scroll. Top toolbars don't scroll either.

* **What is the expected behavior?**

Being able to style md-content to manage heights and widths of components within it.
Adding a `height: inherit` for `md-content`fixes the issue, but I'm not sure hard coding this would be the best solution.

* **What is the motivation / use case for changing the behavior?**

Taking control of how scrolling affects each part of the whole layout. Currently it's an all or nothing approach

* **Which version of Angular and Material, and which browser and OS does this issue affect?**
Did this work in previous versions of Angular / Material?

Material2: 2.0.0-alpha.4
Angular: rc01
