### ISSUE TITLE
Change color of datetimepicker toggle

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#4934]
#### feature request:
I would like to change the color of the datetime picker toggle. The default color is black and i see i'ts an image and not a font.

#### What is the expected behavior?
Add an attribute **[toggleColor]="Primary"**
`<md-datepicker #dateStart startView="year" [startAt]="start" [toggleColor]="Primary"></md-datepicker>`

**Comment by willshowell** [comment]
Related, you can't make it gray when disabled... I've been having to set the opacity instead

```scss
.mat-datepicker-toggle[disabled] {
  opacity: 0.38;
}
```
