### ISSUE TITLE
Improve slide-toggle text label

### ISSUE THREAD

**Issue by ocarreterom** [angular/material2#5212]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
The text of the slide-toggle should wrap or be ellipsed like md-checkbox.

#### What is the current behavior?
The label push de content out of its parent.

#### What are the steps to reproduce?
Demo: http://plnkr.co/edit/MZ3fzeJKCyBvGIBphl2P?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material: 2.0.0-beta.6-0aaeb69

#### Is there anything else we should know?
¿Remove `white-space: nowrap`?

**Comment by DevVersion** [comment]
I think there was a reason why we didn't do that. I will try to figure out why.

**Comment by DevVersion** [comment]
The reason I didn't add the text ellipsis to the slide-toggle was that the label of the slide-toggle does have a dynamic width (and therefore the ellipsis couldn't work properly)

There are workarounds for flexbox containers to properly show a text ellipsis.

```scss
.mat-slide-toggle-label {
  flex: 1;

  * {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
}
```

@jelbourn Do you think we should do something like that? I feel like it's not good to reach out of the components view (with the CSS selector)
