### ISSUE TITLE
[user error] mat-contrast always return contrast of 500 when hue=default instead of the correct value

### ISSUE THREAD

**Issue by thibaultsavary** [angular/material2#6022]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-contrast should return the contrast calculated with the given hue.

#### What is the current behavior?
mat-contrast always return the contrast calculated with the predefined default hue.

#### What are the steps to reproduce?
Example
`theme.scss`
```scss
@import '~@angular/material/theming';
@include mat-core();
$primary: mat-palette($mat-teal, 300, 100, 500);
$accent: mat-palette($mat-deep-purple, 300, 100, 500);
$warn: mat-palette($mat-deep-orange);
$theme: mat-dark-theme($primary, $accent, $warn);
@include angular-material-theme($theme);
@mixin app-theme($theme) {
    $primary: map-get($theme, primary);
    $accent: map-get($theme, accent);
    $warn: map-get($theme, warn);
    $background: map-get($theme, 'background');
}
```
`some-component.scss`
```scss
// ...
element {
  color: mat-contrast($primary, default);
}
// ...
```
In this case the expected value for `default` is `300` however the contrast returned correspond to `500`.

#### What is the use-case or motivation for changing an existing behavior?
Not everybody uses the `500` hue as default.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```ts
@angular/cli: 1.2.1
node: 8.1.4
os: win32 x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1
```

#### Is there anything else we should know?
No

**Comment by thibaultsavary** [comment]
using this 
```scss
element {
  color: mat-color($primary, default-contrast);
}
```
instead of 
```scss
element {
  color: mat-contrast($primary, default);
}
```
solved the issue
