### ISSUE TITLE
md-input-container invalid font

### ISSUE THREAD

**Issue by henriquecustodia** [angular/material2#6375]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
`md-input-container` component has to use a valid font value for the class `.mat-input-container`

#### What is the current behavior?
`md-input-container` component  using an invalid font value for the class `.mat-input-container`

```css
.mat-input-container {
    font: 400 inherit/1.125 Roboto, "Helvetica Neue", sans-serif;
}
```

#### What are the steps to reproduce?
Same steps that issue [#5262](https://github.com/angular/material2/issues/5262)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: Ubuntu 16.04
Angular: 4.3.3
Typescript: 2.2.0
"@angular/material": "2.0.0-beta.8",

browsers: Chrome, Chromium

#### Is there anything else we should know?
I think this problem was fixed last month but is it in beta.8 release?

Thanks.
