### ISSUE TITLE
md-menu with many items does not show the last element on mobile

### ISSUE THREAD

**Issue by adamdport** [angular/material2#6698]
#### Bug, feature request, or proposal:
When an md-menu has enough items to require scrolling, the last item cannot be scrolled to.

#### What is the expected behavior?
All items can be seen/clicked

#### What is the current behavior?
The last item is hidden

#### What are the steps to reproduce?
http://plnkr.co/edit/cXYMiLCQKQKeii1RiH2z

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Happens on Chrome on Android and Safari on iOS

#### Is there anything else we should know?
This possibly duplicates #6396. That issue however is far more complicated and includes fixed positioning, custom styling, images in the menu, etc, which I wouldn't expect to be supported.

**Comment by isaacplmann** [comment]
This happens on desktop too, if the window height is not tall enough to fit the whole md-menu.  And it is exacerbated if the `[mdMenuTriggerFor]` is clicked when it is lower down on the viewport.

The issue is partially a css issue, but I can't think of a way to solve it entirely with css.

The current css does this:
```css
.cdk-overlay-pane {
  position: absolute;
  top: 100px; // set by javascript
  left: 150px; //set by javascript
}
.mat-menu-panel {
  overflow: auto;
  max-height: calc(100vh - 48px);
}
```

I can't see any reason for `max-height: calc(100vh - 48px)`.  There are two cases that need to be accounted for. (1) the menu is shorter than the height of the viewport or (2) the menu is taller than the height of the viewport.

For the (1) shorter scenario, you can use the existing css.  Potentially removing the un-needed `max-height` line.

For the (2) taller scenario, the css needs to be modified:

```css
.mat-menu-panel {
  overflow: auto;
  position: relative;
  bottom: 0px;
}
```

 OR

```css
.cdk-overlay-pane {
  position: absolute;
  top: 100px; // set by javascript
  left: 150px; //set by javascript
  bottom: 0px;
  overflow: auto;
}
```

Note: if you add the css for the (2) taller scenario when the md-menu is actually (1) shorter, the md-menu always stretches to the bottom of the screen - even when the content doesn't warrant it.

**Comment by isaacplmann** [comment]
Another solution that would handle both scenarios is to do something like this:

```css
.cdk-overlay-pane > div {
  max-height: calc(100vh - 89px);
  // the 89px is the value of top that is set on the cdk-overlay-pane
}
```

**Comment by isaacplmann** [comment]
After reading issue #2725, I see that the `max-height: calc(100vh - 48px)` rule is there to keep the `md-menu` from touching the edge of the viewport.

Given that guideline, the new solution would be this:

```css
.cdk-overlay-pane > div {
  max-height: calc(100vh - 48px - [top/bottom of cdk-overlay-pane]);
}
```
