### ISSUE TITLE
How to align md-icon with text

### ISSUE THREAD

**Issue by Robouste** [angular/material2#7071]
When I tried to put a text next to an icon, I have an alignment problem.

Check [plunkr](http://plnkr.co/edit/P39J9As42SjmXIGuWaVW)

What should I do to get them aligned ? Is there a best practice ? Something I need to do to stay compliant to material guidelines ?

I do not have those problems with other icon library like font awesome. Is there any particular reason for that ?

Changing font-size doesn't make them look better either

**Comment by julianobrasil** [comment]
You can try this:

```css
<style>
  .line-with-icon md-icon {
    font-size: 1rem;
    width: inherit;
    height: 1.2rem;
    vertical-align: middle;
  }
</style>
```
