### ISSUE TITLE
doc(icons) : embed material icons

### ISSUE THREAD

**Issue by merlosy** [angular/material2#7491]
### Documentation

**This is not the recommended approach to add material icons**
But if like me, you have a corporate environment where users are using IE with compatibility mode ON by default, and you realize icons are not rendering at all, you'lI have to include the material icons in your project.
I don't know if this is the right place to drop this but i'll do it here if anyone needs it.

- install: `npm i --save material-design-icons` 

- add to your `angular-cli.json` along with other config : 
```json
{
"apps": [
    "assets": [
       {
          "glob": "MaterialIcons-Regular.woff",
          "input": "../node_modules/material-design-icons/iconfont/",
          "output": "assets/fonts/"
        },
        {
          "glob": "MaterialIcons-Regular.woff2",
          "input": "../node_modules/material-design-icons/iconfont/",
          "output": "assets/fonts/"
        },
        {
          "glob": "MaterialIcons-Regular.ttf",
          "input": "../node_modules/material-design-icons/iconfont/",
          "output": "assets/fonts/"
        },
        {
          "glob": "MaterialIcons-Regular.eot",
          "input": "../node_modules/material-design-icons/iconfont/",
          "output": "assets/fonts/"
        }
    ]
]
}
```

- And add this to your main stylesheet:
```css
@font-face {
    font-family: 'Material Icons';
    font-style: normal;
    font-weight: 400;
    src: url('/assets/fonts/MaterialIcons-Regular.eot');
    /* For IE6-8 */
    src: local('Material Icons'), local('MaterialIcons-Regular'), url('/assets/fonts/MaterialIcons-Regular.woff2') format('woff2'), url('/assets/fonts/MaterialIcons-Regular.woff') format('woff'), url('/assets/fonts/MaterialIcons-Regular.ttf') format('truetype');
}

.material-icons {
    font-family: 'Material Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;
    /* Preferred icon size */
    display: inline-block;
    line-height: 1;
    text-transform: none;
    letter-spacing: normal;
    word-wrap: normal;
    white-space: nowrap;
    direction: ltr;
    /* Support for all WebKit browsers. */
    -webkit-font-smoothing: antialiased;
    /* Support for Safari and Chrome. */
    text-rendering: optimizeLegibility;
    /* Support for Firefox. */
    -moz-osx-font-smoothing: grayscale;
    /* Support for IE. */
    font-feature-settings: 'liga';
}
```

Rgds,
