### ISSUE TITLE
select issues: impossible fluid width, different heights selected vs. empty

### ISSUE THREAD

**Issue by fxck** [angular/material2#7627]
### fixed width on mat-form-field
I want my select to have the width of the selected item, fixed width on mat-form-field makes it impossible, you can override `.mat-form-field` to have `width` `auto`, along with overriding `.mat-select-value` to be `width` `auto` and `max-width` `100%`, but then you have a problem, because placeholder is absolutely positioned, which means that the select will be zero width (actually 18px because of the arrow).

https://stackblitz.com/edit/material2-select-width-issues?file=styles.scss

Now I could also override placeholders not to be absolutely positioned, but that's not gonna work properly either, because the arrow is inside the `md-select` element, while the placeholder is outside

![image](https://user-images.githubusercontent.com/1303561/31315390-330fa1e6-ac18-11e7-8b95-a19923299262.png)

I'm not sure if that 200px width is something that's on material spec, but the DOM could perhaps be structured a bit differently, in a way that wouldn't prevent devs from achieving fluid width (which is a bit closer to how native selects work)

# different height when selected vs. placeholder 
![image](https://user-images.githubusercontent.com/1303561/31315458-4a4e4276-ac19-11e7-8d0d-98b9058da2c7.png)

cc @crisbeto

**Comment by willshowell** [comment]
This seems to workaround the differences in heights

```css
.mat-select {
  height: 1.125em;
}
```

**Comment by fxck** [comment]
also what's on current master has `mat-form-field-infix` fixed width to 180px 

@crisbeto @mmalerba

**Comment by mmalerba** [comment]
I believe the height issue was caused by an `&nbsp;` not rendering correctly. It was fixed with https://github.com/angular/material2/pull/7431 by updating Angular to a version that fixed the bug. The width was added so the select would have a correct initial width, but it should still resize to fit the form field. Here's a plunker demonstrating both behaviors working without any special CSS: http://plnkr.co/edit/xugYuUx3dY50lTnDu7HB?p=preview

**Comment by fxck** [comment]
@mmalerba it resizes to fit the form field, but form field doesn't fit its parent (which causes problems, see https://github.com/angular/material2/issues/7783).

Anyway, what I'm talking about in this issue (regarding the width) is having select to be only the **width of it's content (either selected value, or placeholder)**.. currently it's either fixed to whatever mat-form-field width is or 100% of parent. 

You can override it (https://stackblitz.com/edit/material2-select-width-issues-vedgpg?file=styles.scss) but it's not gonna work with placeholders, because they are absolutely positioned. I'm currently getting around it (since I don't need floating placeholders in this particular case) by using the first option without any value set as a a placeholder.. not ideal.

**Comment by mmalerba** [comment]
Ok, I've changed the title of the issue to reflect just the width issue, since the height should be resolved

**Comment by tcrite** [comment]
Something else that should be noted with those css overrides is that you lose the text truncating and ellipsis when you resize the screen

**Comment by laike9m** [comment]
This is p3??

**Comment by KleptoKat** [comment]
The best workaround I found to fix both value and placeholder was to use ::ng-deep and set a different min-width on .mat-select-placeholder and setting width: fit-content on .mat-select-value and mat-select.

Since ng-deep will be deprecated soon this is not a permanent solution but one that works until this issue is resolved.

Full example:

```scss
mat-select {
    width: fit-content !important;
    min-width: 100%;
}

::ng-deep .mat-form-field-infix {
    min-width: 75px !important;
    width: fit-content !important;
}

::ng-deep mat-select .mat-select-value {
    width: fit-content;
    min-width: 2ch;
    max-width: 25ch;
}
::ng-deep mat-select .mat-select-placeholder {
    width: fit-content;
    min-width: 10ch;
}

```
