### ISSUE TITLE
data-table styling, incorrect styling if cdk-cell use static width 

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material2#9027]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
if cells has static width, scrolling appears and all content inside should have same styles.

#### What is the current behavior?
if cells has static width, scrolling appears and all content that out of view has no correct styles.

#### What are the steps to reproduce?
view: https://angular-g5gfng-yw7aey.stackblitz.io/
editor: https://stackblitz.com/edit/angular-g5gfng-yw7aey
Just scroll horizontally and you'll see that styles are broken.

#### What is the use-case or motivation for changing an existing behavior?
I'm using app where i need dynamically change displayed columns, so when i show all columns on mobile this issue appears

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular: 5+, 
material: 5+,
os: windows, ios 
browser: chrome, IE11 - EDGE
TypeScript: doesn't matter 

#### Is there anything else we should know?
nope

Thank you

**Comment by todoubaba** [comment]
```css
.example-container {
  display: flex;
  flex-direction: column;
  width: 200px;
  overflow: auto; /*<-*/
}

.example-table {
  flex: 1 1 auto;
  /* overflow: auto; */ /*<-*/
  max-height: 500px;
  display: table; /*<-*/
}
```
