### ISSUE TITLE
Mat-Table text vertical alignment wrong in IE 11 browser

### ISSUE THREAD

**Issue by jayakrishna-v** [angular/material2#9142]
#### What are the steps to reproduce?
Check the official mat-table link below.
https://material.angular.io/components/table/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
IE 11 browser. Angular version 5

**Comment by oktav777** [comment]
`flexbox` and `min-height` not working together in IE, you have 2 options:
1. Set a fixed height for rows:
```css
.mat-header-row, .mat-row {
    min-height: 0;
    height: 48px;
}
```
2. Add a flex parent, so it will use the min-height set on children:
```css
.mat-table {
    display: flex;
    flex-direction: column;
}
```
