### ISSUE TITLE
Fixed header in mat-table

### ISSUE THREAD

**Issue by jayakrishna-v** [angular/material2#9143]
#### What are the steps to reproduce?
Check the official mat-table link below.
https://material.angular.io/components/table/overview

#### What is the use-case or motivation for changing an existing behavior?
When we had to show more than 50 records per page, user will have to scroll down to see the bottom records. When we scroll down, header should stay static on top of the table and it helps the user to easily identify which column is what.

**Comment by jayakrishna-v** [comment]
found a sample

**Comment by jayakrishna-v** [comment]
No working sample available

**Comment by oktav777** [comment]
```css
.mat-header-row {
    position: sticky;
    top: 0;
    background-color: inherit;
}
```

**Comment by Chan4077** [comment]
@oktav777 You should also include `position: -webkit-sticky` for Safari browsers.
```css
.mat-header-row {
    position: sticky;
    position: -webkit-sticky;
    top: 0;
    background-color: inherit;
}
```

**Comment by oktav777** [comment]
@Chan4077 preprocessor should autoprefix it.

**Comment by stevenmi** [comment]
@oktav777  the css work .but if the hearder has  selection,when scroll the below will occur

before scoll:
![tim 20171228154817](https://user-images.githubusercontent.com/14286935/34404003-9063114e-ebe6-11e7-85c0-93cbe9bcc616.png)

when scroll:
![tim 20171228154732](https://user-images.githubusercontent.com/14286935/34403976-72236878-ebe6-11e7-9af6-475f4dea9075.png)

**Comment by jayakrishna-v** [comment]
Thanks oktav and Chan. The css works fine. But not working in IE 11

**Comment by oktav777** [comment]
@stevenmi add `z-index` so it looks like: 
```css
.mat-header-row {
    top: 0;
    position: sticky;
    z-index: 1;
    background-color: inherit;
}
```
