### ISSUE TITLE
Proposal: Add an enclosed input variant aka Solo fields

### ISSUE THREAD

**Issue by bettercalldough** [angular/material2#9235]
#### Bug, feature request, or proposal:
Proposal

#### What is the use-case or motivation for changing an existing behavior?
Input on Material2 does not currently support a [Solo Field](https://material.io/guidelines/components/text-fields.html#text-fields-field-variations) which is currently in the Material Guidelines.

When a text field is used for a single action such as search, the text field may be elevated, with associated icons placed within it. An input line is not required.

On desktop, a raised search button should appear to the right of the search field.

I have attached a component I am working on currently.

<img width="453" alt="screen shot 2018-01-04 at 18 37 42" src="https://user-images.githubusercontent.com/22435712/34578988-0cce6c54-f17f-11e7-8cc2-89527d73f51d.png">

**Comment by leocaseiro** [comment]
We can accomplish that with a few CSS and the following HTML:

```html
<mat-form-field floatLabel="never" class="mat-elevation-z4 mat-form-field--solo">
  <input matInput placeholder="Search">
  <button matSuffix mat-icon-button>
    <mat-icon  aria-label="Search">search</mat-icon>
  </button>
</mat-form-field>
```

```css
.mat-form-field--solo {
  padding: 0 16px;
  margin: 16px;
}

.mat-form-field--solo .mat-input-underline,
.mat-form-field--solo .mat-form-field-underline {
  display: none !important;
}
.mat-form-field-wrapper {
  padding-bottom: 1em;
}
```

See example: https://angular-material2-issue-fyjskp.stackblitz.io
