### ISSUE TITLE
Docs missing for "fullscreen"

### ISSUE THREAD

**Issue by mackelito** [angular/material2#9413]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Docs on how to use fullscreen and what it does and when it use it (perhaps also explain potential downsides)

#### What is the current behavior?
Docs for fullscreen is missing

**Comment by Chan4077** [comment]
@mackelito The `fullscreen` attribute is just used to make the sidenav container appear fullscreen and to not have a "margin" around the sidenav container.

It uses this to style the sidenav container (Btw, I'm using the latest version of Angular Material `5.0.4`):
```css
.mat-drawer-container[fullscreen] {
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	position: absolute;
}
```
