### ISSUE TITLE
Full screen dialog in mobile mode

### ISSUE THREAD

**Issue by AccessViolator** [angular/material2#9823]
#### Bug, feature request, or proposal:
A bug to me

#### What is the expected behavior?
Being able to have full screen dialogs by overriding `cdk-overlay-pane` class

#### What is the current behavior?
Not possible because framework adds `max-width: 80vw;` to element's `style`

#### What are the steps to reproduce?
Override `cdk-overlay-pane` with `width: 100%` and see it ignored because of `max-width: 80vw;` in the `style`

#### What is the use-case or motivation for changing an existing behavior?
Displaying html blobs of site's T&C and privacy policy. May not the best way to use dialogs, but nonetheless...

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.3, Material 5.2.0

#### Is there anything else we should know?
I'm upgrading a site from an early 2.0.0.beta8 where this was possible.

**Comment by willshowell** [comment]
I hadn't noticed this change, but I used to use this and it was working fine:

```scss
.my-full-screen-dialog .mat-dialog-container {
  max-width: none;
  width: 100vw;
  height: 100vh;
}
```

Now it seems `!important` is the best I can do 😕

```scss
.my-full-screen-dialog {
  height: 100vh;
  width: 100vw !important;
  max-width: none !important;
}
```
