### ISSUE TITLE
Datatable inside Stepper: whitespaces between border and table

### ISSUE THREAD

**Issue by taokakao** [angular/material2#9937]
#### Bug

When placing data table inside stepper there are whitespaces between table and borders.

#### What is the expected behavior?

No whitespaces between border and table.

#### What is the current behavior?

<img width="646" alt="screen shot 2018-02-14 at 11 30 35" src="https://user-images.githubusercontent.com/1310147/36196870-b5cd8a4a-117a-11e8-9d43-fa12870a6c1f.png">

#### What are the steps to reproduce?

Put data table inside stepper.

#### What else to know?

mat-card-image doesn't help :-)

**Comment by julianobrasil** [comment]
Yeah... the low contrast in the image doesn't help. Can you provide a stackblitz demo, maybe overriding the colors?

**Comment by julianobrasil** [comment]
There's no need for stackblitz demo, the second image is pretty unambiguous 😄. In the code, there's a 24px on both sides of the stepper. It looks like it's in [material design specs](https://material.io/guidelines/components/steppers.html#steppers-specs).

You can override it by setting **globally** (`styles.css` or some other global styling file you have):

for the stepper header:
```css
.my-class .mat-horizontal-stepper-header-container .mat-horizontal-stepper-header {
  padding: 0px;
}
```

for the container:

```css
.my-class .mat-horizontal-content-container {
  padding: 0px;
}
```

where `my-class` is applied to the `<stepper>` element, for example:

```html
<mat-horizontal-stepper class="my-class">

</mat-horizontal-stepper>
```
